// Generated by the Supabase MCP `generate_typescript_types` tool.
// Regenerate after any schema migration rather than hand-editing.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      cook_log: {
        Row: {
          cooked_at: string
          id: string
          recipe_id: string | null
        }
        Insert: {
          cooked_at?: string
          id?: string
          recipe_id?: string | null
        }
        Update: {
          cooked_at?: string
          id?: string
          recipe_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "cook_log_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      cooking_methods: {
        Row: {
          id: string
          name: string
          sort_order: number
        }
        Insert: {
          id?: string
          name: string
          sort_order?: number
        }
        Update: {
          id?: string
          name?: string
          sort_order?: number
        }
        Relationships: []
      }
      recipe_cooking_methods: {
        Row: {
          cooking_method_id: string
          recipe_id: string
        }
        Insert: {
          cooking_method_id: string
          recipe_id: string
        }
        Update: {
          cooking_method_id?: string
          recipe_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "recipe_cooking_methods_cooking_method_id_fkey"
            columns: ["cooking_method_id"]
            isOneToOne: false
            referencedRelation: "cooking_methods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "recipe_cooking_methods_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      ingredients: {
        Row: {
          id: string
          item: string
          quantity: number | null
          recipe_id: string | null
          sort_order: number
          unit: string | null
        }
        Insert: {
          id?: string
          item: string
          quantity?: number | null
          recipe_id?: string | null
          sort_order?: number
          unit?: string | null
        }
        Update: {
          id?: string
          item?: string
          quantity?: number | null
          recipe_id?: string | null
          sort_order?: number
          unit?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ingredients_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      recipes: {
        Row: {
          cook_time_minutes: number | null
          created_at: string | null
          id: string
          image_url: string | null
          notes: string | null
          prep_time_minutes: number | null
          servings: number | null
          source_url: string | null
          title: string
          updated_at: string | null
        }
        Insert: {
          cook_time_minutes?: number | null
          created_at?: string | null
          id?: string
          image_url?: string | null
          notes?: string | null
          prep_time_minutes?: number | null
          servings?: number | null
          source_url?: string | null
          title: string
          updated_at?: string | null
        }
        Update: {
          cook_time_minutes?: number | null
          created_at?: string | null
          id?: string
          image_url?: string | null
          notes?: string | null
          prep_time_minutes?: number | null
          servings?: number | null
          source_url?: string | null
          title?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      steps: {
        Row: {
          id: string
          instruction: string
          recipe_id: string | null
          step_number: number
        }
        Insert: {
          id?: string
          instruction: string
          recipe_id?: string | null
          step_number: number
        }
        Update: {
          id?: string
          instruction?: string
          recipe_id?: string | null
          step_number?: number
        }
        Relationships: [
          {
            foreignKeyName: "steps_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

type DefaultSchema = Database["public"]

export type Tables<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Row"]

export type TablesInsert<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Insert"]

export type TablesUpdate<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Update"]

// Convenience aliases used throughout the app.
export type Recipe = Tables<"recipes">
export type Ingredient = Tables<"ingredients">
export type Step = Tables<"steps">
export type CookingMethod = Tables<"cooking_methods">
export type CookLogEntry = Tables<"cook_log">

export type RecipeWithRelations = Recipe & {
  ingredients: Ingredient[]
  steps: Step[]
}

/** A recipe as rendered on the grid: methods attached, no ingredients/steps. */
export type RecipeCardData = Recipe & {
  cooking_methods: CookingMethod[]
}
